[package]
name = "nix-software-center"
authors = ["Victor Fuentes <vlinkz@snowflakeos.org>"]
edition = "2024"
version = "0.2.0-alpha.1"

[profile.release]
lto = true

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.10", package = "gtk4", features = ["v4_8"] }
adw = { version = "0.8.1", package = "libadwaita", features = ["v1_8"] }
tracing = "0.1.37"
tracing-subscriber = "0.3"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.13", features = ["json", "brotli"] }
libsnow = { git = "https://github.com/snowfallorg/libsnow" }
libappstream = "0.4"
async-channel = "2"
